<!ENTITY % fontset-settings SYSTEM "fontset.xml.inc">
%fontset-settings;
<!ENTITY % entities-common SYSTEM "entities.xml.inc">
%entities-common;

<!-- site specific settings -->

<!ENTITY prefix "planet_osm">
<!ENTITY datasource-settings SYSTEM "db_global.xml.inc">
<!ENTITY walls "yes">
<!ENTITY rail "yes">
<!ENTITY driveway "#01010101">
<!ENTITY contourSeparation "10">
<!ENTITY layers-contours SYSTEM "layers_contours_maposmatic.xml.inc">
